language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"

env:
  - DJANGO="django==1.6 --use-mirrors"
  - DJANGO="django==1.5.5 --use-mirrors"

install:
  - pip install $DJANGO
  - pip install djangorestframework django-nose mock --use-mirrors
  - export PYTHONPATH=.

script:
  - python rest_utils/runtests/runtests.py
